import Foundation

public struct AssistantMessage: Codable, Hashable, Sendable {
    /// This is the role of the message author
    public let role: Assistant
    /// This is the content of the assistant message
    public let content: String?
    /// This is the refusal message generated by the model
    public let refusal: String?
    /// This is the tool calls generated by the model
    public let toolCalls: [ToolCall]?
    /// This is an optional name for the participant
    public let name: String?
    /// This is an optional metadata for the message
    public let metadata: [String: JSONValue]?
    /// Additional properties that are not explicitly defined in the schema
    public let additionalProperties: [String: JSONValue]

    public init(
        role: Assistant,
        content: String? = nil,
        refusal: String? = nil,
        toolCalls: [ToolCall]? = nil,
        name: String? = nil,
        metadata: [String: JSONValue]? = nil,
        additionalProperties: [String: JSONValue] = .init()
    ) {
        self.role = role
        self.content = content
        self.refusal = refusal
        self.toolCalls = toolCalls
        self.name = name
        self.metadata = metadata
        self.additionalProperties = additionalProperties
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.role = try container.decode(Assistant.self, forKey: .role)
        self.content = try container.decodeIfPresent(String.self, forKey: .content)
        self.refusal = try container.decodeIfPresent(String.self, forKey: .refusal)
        self.toolCalls = try container.decodeIfPresent([ToolCall].self, forKey: .toolCalls)
        self.name = try container.decodeIfPresent(String.self, forKey: .name)
        self.metadata = try container.decodeIfPresent([String: JSONValue].self, forKey: .metadata)
        self.additionalProperties = try decoder.decodeAdditionalProperties(using: CodingKeys.self)
    }

    public func encode(to encoder: Encoder) throws -> Void {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try encoder.encodeAdditionalProperties(self.additionalProperties)
        try container.encode(self.role, forKey: .role)
        try container.encodeIfPresent(self.content, forKey: .content)
        try container.encodeIfPresent(self.refusal, forKey: .refusal)
        try container.encodeIfPresent(self.toolCalls, forKey: .toolCalls)
        try container.encodeIfPresent(self.name, forKey: .name)
        try container.encodeIfPresent(self.metadata, forKey: .metadata)
    }

    public enum Assistant: String, Codable, Hashable, CaseIterable, Sendable {
        case assistant
    }

    /// Keys for encoding/decoding struct properties.
    enum CodingKeys: String, CodingKey, CaseIterable {
        case role
        case content
        case refusal
        case toolCalls = "tool_calls"
        case name
        case metadata
    }
}