import Foundation

/// This is the mode for the first message. Default is 'assistant-speaks-first'.
/// 
/// Use:
/// - 'assistant-speaks-first' to have the assistant speak first.
/// - 'assistant-waits-for-user' to have the assistant wait for the user to speak first.
/// - 'assistant-speaks-first-with-model-generated-message' to have the assistant speak first with a message generated by the model based on the conversation state. (`assistant.model.messages` at call start, `call.messages` at squad transfer points).
/// 
/// @default 'assistant-speaks-first'
public enum AssistantFirstMessageMode: String, Codable, Hashable, CaseIterable, Sendable {
    case assistantSpeaksFirst = "assistant-speaks-first"
    case assistantSpeaksFirstWithModelGeneratedMessage = "assistant-speaks-first-with-model-generated-message"
    case assistantWaitsForUser = "assistant-waits-for-user"
}