import Foundation

/// The voices provided by Vapi
public enum FallbackVapiVoiceVoiceId: String, Codable, Hashable, CaseIterable, Sendable {
    case clara = "Clara"
    case godfrey = "Godfrey"
    case layla = "Layla"
    case sid = "Sid"
    case gustavo = "Gustavo"
    case elliot = "Elliot"
    case kylie = "Kylie"
    case rohan = "Rohan"
    case lily = "Lily"
    case savannah = "Savannah"
    case hana = "Hana"
    case neha = "Neha"
    case cole = "Cole"
    case harry = "Harry"
    case paige = "Paige"
    case spencer = "Spencer"
    case nico = "Nico"
    case kai = "Kai"
    case emma = "Emma"
    case sagar = "Sagar"
    case neil = "Neil"
    case naina = "Naina"
    case leah = "Leah"
    case tara = "Tara"
    case jess = "Jess"
    case leo = "Leo"
    case dan = "Dan"
    case mia = "Mia"
    case zac = "Zac"
    case zoe = "Zoe"
}