import Foundation

/// Language hint for MiniMax T2A. Example: yue (Cantonese), zh (Chinese), en (English).
public enum FallbackMinimaxVoiceLanguageBoost: String, Codable, Hashable, CaseIterable, Sendable {
    case chinese = "Chinese"
    case chineseYue = "Chinese,Yue"
    case english = "English"
    case arabic = "Arabic"
    case russian = "Russian"
    case spanish = "Spanish"
    case french = "French"
    case portuguese = "Portuguese"
    case german = "German"
    case turkish = "Turkish"
    case dutch = "Dutch"
    case ukrainian = "Ukrainian"
    case vietnamese = "Vietnamese"
    case indonesian = "Indonesian"
    case japanese = "Japanese"
    case italian = "Italian"
    case korean = "Korean"
    case thai = "Thai"
    case polish = "Polish"
    case romanian = "Romanian"
    case greek = "Greek"
    case czech = "Czech"
    case finnish = "Finnish"
    case hindi = "Hindi"
    case bulgarian = "Bulgarian"
    case danish = "Danish"
    case hebrew = "Hebrew"
    case malay = "Malay"
    case persian = "Persian"
    case slovak = "Slovak"
    case swedish = "Swedish"
    case croatian = "Croatian"
    case filipino = "Filipino"
    case hungarian = "Hungarian"
    case norwegian = "Norwegian"
    case slovenian = "Slovenian"
    case catalan = "Catalan"
    case nynorsk = "Nynorsk"
    case tamil = "Tamil"
    case afrikaans = "Afrikaans"
    case auto
}