import Foundation

/// This is the language that will be set for the transcription. The list of languages Whisper supports can be found here: https://github.com/openai/whisper/blob/main/whisper/tokenizer.py
public enum FallbackTalkscriberTranscriberLanguage: String, Codable, Hashable, CaseIterable, Sendable {
    case en
    case zh
    case de
    case es
    case ru
    case ko
    case fr
    case ja
    case pt
    case tr
    case pl
    case ca
    case nl
    case ar
    case sv
    case it
    case id
    case hi
    case fi
    case vi
    case he
    case uk
    case el
    case ms
    case cs
    case ro
    case da
    case hu
    case ta
    case no
    case th
    case ur
    case hr
    case bg
    case lt
    case la
    case mi
    case ml
    case cy
    case sk
    case te
    case fa
    case lv
    case bn
    case sr
    case az
    case sl
    case kn
    case et
    case mk
    case br
    case eu
    case `is`
    case hy
    case ne
    case mn
    case bs
    case kk
    case sq
    case sw
    case gl
    case mr
    case pa
    case si
    case km
    case sn
    case yo
    case so
    case af
    case oc
    case ka
    case be
    case tg
    case sd
    case gu
    case am
    case yi
    case lo
    case uz
    case fo
    case ht
    case ps
    case tk
    case nn
    case mt
    case sa
    case lb
    case my
    case bo
    case tl
    case mg
    case `as`
    case tt
    case haw
    case ln
    case ha
    case ba
    case jw
    case su
    case yue
}