import Foundation

/// This is the language that will be set for the transcription.
public enum GoogleTranscriberLanguage: String, Codable, Hashable, CaseIterable, Sendable {
    case multilingual = "Multilingual"
    case arabic = "Arabic"
    case bengali = "Bengali"
    case bulgarian = "Bulgarian"
    case chinese = "Chinese"
    case croatian = "Croatian"
    case czech = "Czech"
    case danish = "Danish"
    case dutch = "Dutch"
    case english = "English"
    case estonian = "Estonian"
    case finnish = "Finnish"
    case french = "French"
    case german = "German"
    case greek = "Greek"
    case hebrew = "Hebrew"
    case hindi = "Hindi"
    case hungarian = "Hungarian"
    case indonesian = "Indonesian"
    case italian = "Italian"
    case japanese = "Japanese"
    case korean = "Korean"
    case latvian = "Latvian"
    case lithuanian = "Lithuanian"
    case norwegian = "Norwegian"
    case polish = "Polish"
    case portuguese = "Portuguese"
    case romanian = "Romanian"
    case russian = "Russian"
    case serbian = "Serbian"
    case slovak = "Slovak"
    case slovenian = "Slovenian"
    case spanish = "Spanish"
    case swahili = "Swahili"
    case swedish = "Swedish"
    case thai = "Thai"
    case turkish = "Turkish"
    case ukrainian = "Ukrainian"
    case vietnamese = "Vietnamese"
}