import Foundation

/// MAI-Voice-2 voice ID. Built-in voices listed in enum.
public enum MicrosoftVoiceVoiceId: String, Codable, Hashable, CaseIterable, Sendable {
    case deDeKlausMaiVoice2 = "de-DE-Klaus:MAI-Voice-2"
    case deDeMiaMaiVoice2 = "de-DE-Mia:MAI-Voice-2"
    case enAuLisaMaiVoice2 = "en-AU-Lisa:MAI-Voice-2"
    case enUsEthanMaiVoice2 = "en-US-Ethan:MAI-Voice-2"
    case enUsGrantMaiVoice2 = "en-US-Grant:MAI-Voice-2"
    case enUsHarperMaiVoice2 = "en-US-Harper:MAI-Voice-2"
    case enUsIrisMaiVoice2 = "en-US-Iris:MAI-Voice-2"
    case enUsJasperMaiVoice2 = "en-US-Jasper:MAI-Voice-2"
    case enUsOliviaMaiVoice2 = "en-US-Olivia:MAI-Voice-2"
    case esEsMartaMaiVoice2 = "es-ES-Marta:MAI-Voice-2"
    case esMxAlejoMaiVoice2 = "es-MX-Alejo:MAI-Voice-2"
    case esMxValeriaMaiVoice2 = "es-MX-Valeria:MAI-Voice-2"
    case frFrMarcMaiVoice2 = "fr-FR-Marc:MAI-Voice-2"
    case frFrSoleilMaiVoice2 = "fr-FR-Soleil:MAI-Voice-2"
    case hiInArjunMaiVoice2 = "hi-IN-Arjun:MAI-Voice-2"
    case hiInDhruvMaiVoice2 = "hi-IN-Dhruv:MAI-Voice-2"
    case hiInKavyaMaiVoice2 = "hi-IN-Kavya:MAI-Voice-2"
    case hiInPriyaMaiVoice2 = "hi-IN-Priya:MAI-Voice-2"
    case huHuBenceMaiVoice2 = "hu-HU-Bence:MAI-Voice-2"
    case huHuLeventeMaiVoice2 = "hu-HU-Levente:MAI-Voice-2"
    case huHuLillaMaiVoice2 = "hu-HU-Lilla:MAI-Voice-2"
    case huHuRekaMaiVoice2 = "hu-HU-Réka:MAI-Voice-2"
    case itItLucaMaiVoice2 = "it-IT-Luca:MAI-Voice-2"
    case itItRosaMaiVoice2 = "it-IT-Rosa:MAI-Voice-2"
    case koKrHanaMaiVoice2 = "ko-KR-Hana:MAI-Voice-2"
    case koKrJunhoMaiVoice2 = "ko-KR-Junho:MAI-Voice-2"
    case nlNlFleurMaiVoice2 = "nl-NL-Fleur:MAI-Voice-2"
    case nlNlSanderMaiVoice2 = "nl-NL-Sander:MAI-Voice-2"
    case ptBrCaioMaiVoice2 = "pt-BR-Caio:MAI-Voice-2"
    case ptBrLuanaMaiVoice2 = "pt-BR-Luana:MAI-Voice-2"
    case ptBrPedroMaiVoice2 = "pt-BR-Pedro:MAI-Voice-2"
    case ptBrRafaelMaiVoice2 = "pt-BR-Rafael:MAI-Voice-2"
    case ptPtRuiMaiVoice2 = "pt-PT-Rui:MAI-Voice-2"
    case roRoAndreiMaiVoice2 = "ro-RO-Andrei:MAI-Voice-2"
    case roRoElenaMaiVoice2 = "ro-RO-Elena:MAI-Voice-2"
    case roRoIoanaMaiVoice2 = "ro-RO-Ioana:MAI-Voice-2"
    case roRoRaduMaiVoice2 = "ro-RO-Radu:MAI-Voice-2"
    case ruRuLevMaiVoice2 = "ru-RU-Lev:MAI-Voice-2"
    case ruRuMashaMaiVoice2 = "ru-RU-Masha:MAI-Voice-2"
    case thThKritMaiVoice2 = "th-TH-Krit:MAI-Voice-2"
    case thThNattapongMaiVoice2 = "th-TH-Nattapong:MAI-Voice-2"
    case trTrAydinMaiVoice2 = "tr-TR-Aydin:MAI-Voice-2"
    case trTrElifMaiVoice2 = "tr-TR-Elif:MAI-Voice-2"
    case zhCnBoMaiVoice2 = "zh-CN-Bo:MAI-Voice-2"
    case zhCnLanMaiVoice2 = "zh-CN-Lan:MAI-Voice-2"
    case zhCnMeiMaiVoice2 = "zh-CN-Mei:MAI-Voice-2"
}