import Foundation

/// This is the message that will be spoken to the user.
/// 
/// If this is not returned, assistant will speak:
/// 1. a `request-complete` or `request-failed` message from `tool.messages`, if it exists
/// 2. a response generated by the model, if not
public enum ToolCallResultSpokenMessage: Codable, Hashable, Sendable {
    case requestComplete(ToolMessageComplete)
    case requestFailed(ToolMessageFailed)

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let discriminant = try container.decode(String.self, forKey: .type)
        switch discriminant {
        case "request-complete":
            self = .requestComplete(try ToolMessageComplete(from: decoder))
        case "request-failed":
            self = .requestFailed(try ToolMessageFailed(from: decoder))
        default:
            throw DecodingError.dataCorrupted(
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unknown shape discriminant value: \(discriminant)"
                )
            )
        }
    }

    public func encode(to encoder: Encoder) throws -> Void {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case .requestComplete(let data):
            try container.encode("request-complete", forKey: .type)
            try data.encode(to: encoder)
        case .requestFailed(let data):
            try container.encode("request-failed", forKey: .type)
            try data.encode(to: encoder)
        }
    }

    enum CodingKeys: String, CodingKey, CaseIterable {
        case type
    }
}